# Coverage configuration for Okie project
coverage:
  status:
    project:
      default:
        target: 20%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "**/*.test.*"
  - "**/*.spec.*"
  - "**/*.config.*"
  - "**/*.d.ts"
  - ".next/"
  - "coverage/"
  - "playwright.config.ts"
  - "vitest.config.mts"
  - "tailwind.config.ts"
  - "postcss.config.mjs"
