export const API_ROUTE_CHAT = "/api/chat"
export const API_ROUTE_CREATE_CHAT = "/api/create-chat"
export const API_ROUTE_CREATE_CHAT_WITH_AGENT = "/api/create-chat-agent"
export const API_ROUTE_CREATE_GUEST = "/api/create-guest"
export const API_ROUTE_UPDATE_CHAT_MODEL = "/api/update-chat-model"
export const API_ROUTE_CSRF = "/api/csrf"
