export const API_ROUTE_CHAT = "/api/chat"
export const API_ROUTE_CREATE_CHAT = "/api/create-chat"
export const API_ROUTE_CREATE_GUEST = "/api/create-guest"
export const API_ROUTE_UPDATE_CHAT_MODEL = "/api/update-chat-model"
export const API_ROUTE_CSRF = "/api/csrf"
export const API_ROUTE_CREATE_AGENT = "/api/create-agent"
export const API_ROUTE_DELETE_AGENT = "/api/delete-agent"
export const API_ROUTE_UPDATE_CHAT_AGENT = "/api/update-chat-agent"
